// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlyeyA3Y8eYeEI7TBOyVqC8eT4glt04Bo',
    appId: '1:1088708711360:web:6cc0d9494ba9c8c79d2e25',
    messagingSenderId: '1088708711360',
    projectId: 'fbtut-6d11c',
    authDomain: 'fbtut-6d11c.firebaseapp.com',
    storageBucket: 'fbtut-6d11c.firebasestorage.app',
    measurementId: 'G-GMXLEFH5PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyyfBxFvEzCeJ79qOEYm0LhIMxhiZ0Buc',
    appId: '1:1088708711360:android:e073aa997a6216739d2e25',
    messagingSenderId: '1088708711360',
    projectId: 'fbtut-6d11c',
    storageBucket: 'fbtut-6d11c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAirwEpDiJq5TDMo9Vy8IDsQQOshhZ5Hs',
    appId: '1:1088708711360:ios:0c230f5a9c8a14b69d2e25',
    messagingSenderId: '1088708711360',
    projectId: 'fbtut-6d11c',
    storageBucket: 'fbtut-6d11c.firebasestorage.app',
    iosBundleId: 'com.jnis.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAirwEpDiJq5TDMo9Vy8IDsQQOshhZ5Hs',
    appId: '1:1088708711360:ios:0c230f5a9c8a14b69d2e25',
    messagingSenderId: '1088708711360',
    projectId: 'fbtut-6d11c',
    storageBucket: 'fbtut-6d11c.firebasestorage.app',
    iosBundleId: 'com.jnis.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlyeyA3Y8eYeEI7TBOyVqC8eT4glt04Bo',
    appId: '1:1088708711360:web:30f27a4873e758c19d2e25',
    messagingSenderId: '1088708711360',
    projectId: 'fbtut-6d11c',
    authDomain: 'fbtut-6d11c.firebaseapp.com',
    storageBucket: 'fbtut-6d11c.firebasestorage.app',
    measurementId: 'G-7DDDE10BN2',
  );
}
